### ISSUE TITLE
Question: do you take PR?

### ISSUE THREAD

**Issue by pettarin** [faroit/awesome-python-scientific-audio#3]
Hi, great idea collecting these resources for Python, thank you.

I have a similar repo, dedicated to open source forced aligners (not just Python):

https://github.com/pettarin/forced-alignment-tools

and some of them --- including my own aeneas --- are written (at least partially) in Python. So my question is: do you take pull requests?

1. If yes, would you mind creating a "forced aligners" subsection, or do you prefer filing them under the current "speech processing"?
2. If not, would you mind adding those you deem interesting (feel free to copy from the list linked above)?

(BTW, you might want to state your contribution policy somewhere in the README, so that you will not get similar queries later.)

**Comment by faroit** [comment]
Hi, sorry that this took so long.

Thanks for your interest. Your list is great. It would nice if you could add some to this list via PR.

> If yes, would you mind creating a "forced aligners" subsection, or do you prefer filing them under the current "speech processing"?

Since I am note sure if many people are familiar with the field of research I would suggest to add them to speech for now. Also I would only add those that directly deal with the speech data and are not purely symbolic. 

> and some of them --- including my own aeneas --- are written (at least partially) in Python. 

thats okay if these are not just accompanying code to your publications

> (BTW, you might want to state your contribution policy somewhere in the README, so that you will not get similar queries later.)

I've added a [contributing.md](https://github.com/faroit/awesome-python-audio-research/blob/master/CONTRIBUTING.md)

**Comment by faroit** [comment]
@pettarin  Feel free to close this and add PR 😄

**Comment by pettarin** [comment]
Hi,

got it, thank you.

This week is busy (Pycon Italy...), I will send a PR next week.

Bests,

AP
